### PR TITLE
Make Scala 3 the default target

### PR DESCRIPTION
**Pull request by smarter**
That way the default will always be the latest released version of
Scala.

### CODE REVIEW

**Comment by smarter** [comment]
Ah, I forgot the worksheet mode doesn't work with Scala 3. What's missing to support that?

**Comment by OlegYch** [comment]
@smarter i guess it might already be working, need to check if latest scalameta supports parsing and formatting it

**Comment by smarter** [comment]
scalameta scala 3 parser is basically complete yeah: https://github.com/scalameta/scalameta/issues/2022

**Comment by SethTisue** [comment]
🎉

**Pull request merged**
