### PR TITLE
Group updates suggested by Steward to run only 1 CI

### PR DESCRIPTION
**Pull request by vincenzobaz**
The first run of Steward found many updates to apply. This PR groups them together so to have only 1 CI run.

Resumes:

 - #552
 - #553
 - #554
 - #555
 - #556
 - #557
 - #558
 - #559
 - #560
 - #561
 - #562
 - #563
 - #564
 - #565
 - #566
 - #567
 - #568
 - #569
 - #570
 - #571
 - #572
 - #573

### CODE REVIEW

**Comment by OlegYch** [comment]
@vincenzobaz i'd deal with sbt separately

**Comment by vincenzobaz** [comment]
It's sbt-docker that causes the issue. Do you think there are breaking changes with sbt?

**Comment by OlegYch** [comment]
@vincenzobaz there could be since we use some internal api, but if you can validate it locally then it's ok
don't forget to update nix build as well though

**Comment by vincenzobaz** [comment]
What should I update in the nix config?

**Comment by OlegYch** [comment]
> This error of `DockerfileBase` and `DockerfileLike` is tricky. An `asInstanceOf` seems to fix it but it is definitely not elegant. How to convert between the two types?

@vincenzobaz pushed a fix

**Comment by vincenzobaz** [comment]
Thanks! I was wondering why were reusing all default params just to change the process...
I will try to have a look at incompats

**Comment by vincenzobaz** [comment]
There a few errors now:

 - https://github.com/scalacenter/scastie/runs/5019683748?check_suite_focus=true#step:6:1589 : it is weird because this should not be affected by libs
 - https://github.com/scalacenter/scastie/runs/5019683748?check_suite_focus=true#step:6:766 : I tried to restart the tests for this one because it is a `Address already in use`

**Comment by OlegYch** [comment]
@vincenzobaz tests seem to pass now
i'll try to deploy later today

**Comment by vincenzobaz** [comment]
Thank you for the help @OlegYch ! I hope it wasn't too annoying to dive into the Akka changelog

**Comment by vincenzobaz** [comment]
Feel free to (squash) and merge if you think it's ready

**Pull request merged**
