### PR TITLE
Add support for Scala 2.13.7

### LINKED ISSUE #537: Support Scala 2.13.7?
happened to notice just now it isn't available in the Scala version dropdown

### PR DESCRIPTION
**Pull request by vincenzobaz**
closes #537

### CODE REVIEW

**Comment by SethTisue** [comment]
Since it's that easy, I've added i to the Scala 2 release steps: scala/scala-dev@cb1e492deabc2825453b7b0745b88aa54e66839d

**Comment by vincenzobaz** [comment]
Great idea @SethTisue. We could also go down the rabbit hole and investigate potential automation of the task

**Comment by OlegYch** [comment]
> 
> 
> Since it's that easy, I've added it to the Scala 2 release steps: [scala/scala-dev@cb1e492](https://github.com/scala/scala-dev/commit/cb1e492deabc2825453b7b0745b88aa54e66839d)

it actually requires updating kind-projector as well https://github.com/scalacenter/scastie/commit/0603528734fb03687ea1f620768686d06e85bbcc

**Comment by SethTisue** [comment]
> it actually requires updating kind-projector as well

ah, good point. I'm adding this to the release steps:

- [ ] Open a ticket in the kind-projector repo, suggesting they publish                                                 
- [ ] Scastie: open PR adding new version (modeled on https://github.com/scalacenter/scastie/pull/538)
  - note that the PR won't be mergeable until kind-projector has published; and if kind-projector's version number has changed, `ScalaTarget.scala` will need updating

**Pull request merged**
