### PR TITLE
Scastie UI redesign

### PR DESCRIPTION
**Pull request by dominv**
This PR contains changes related to the design and responsive support of **Scastie**. These changes are mainly focused in the HTML code generated by the different components and in their respective styles. Nevertheless, there are some components that were modified in order to fit the new UI design.

We’ve been coordinating with Heather and the rest of the Scala Center team during the different stages of this work, receiving feedback from their end on everything from the wireframes design to the actual implementation.

Here is a summary of the primary changes:

- New **Scastie** logo and brand design.

- Full reorganization of the toolbar’s buttons. They are now divided into four different locations:

  - **SideBar Top**: Contains the buttons to access to the two main sections of the application, `Editor` and `Build Settings`.

  - **SideBar Bottom**: The `Theme` and the `Help` buttons can now be found here.

  - **TopBar**: The `Feedback` button (which now contains a drop-down menu to access the Gitter channel and to create an issue in Github) shares this location with the `User` button (which, through its own drop-down menu, will allow the user to access its saved `Code-Snippets` and to log out from the app).

  - **Editor’s TopBar**: This new bar is only shown in the Editor section and contains all the buttons with actions related to the edition or execution of the code.

- The `Console` now can be opened and closed from its own bar.

- New `Welcome`, `Help`, `Share` and `Reset Configuration` modal boxes to show extra information about the application (`Welcome` and `Help`) or to perform extra actions (`Share` and `Reset Configuration`).

- New styles for the `Dark` and `Light` themes, designed to fit the Scala Lang color schemes.

- The changes in the `Code-Snippets` screen are mainly focused on styles but it also now includes a new Share button to copy and share the link associated with each saved snippet.

- In the `Build Settings` section, the order of the subsections has been modified, and a new `Reset Configuration` modal box has been added to confirm the action thrown by the new `Reset` button.

- The application is now fully responsive. For tablet screen sizes, it will only show the actions’ icons and for mobile screen sizes (due to the lack of space) the app will only show the `Editor` (including the `Console`) and two buttons, one to `Run` the code and another one to go to the `Desktop` version where the rest of actions can be performed.
​
@heathermiller @MasseGuillaume could you please review it?

Thanks!

### CODE REVIEW

**Comment by heathermiller** [comment]
AKDHFAKDS!!! 🎉 🎉 ❤️

**Comment by fommil** [comment]
what's the license and trademark status of the logo? If it's using a creative commons license, is it one of the libre ones or a non-commercial / no-derivatives variant? I recommend CC BY-SA as it forces derivatives to also be copyleft.

**Comment by MasseGuillaume** [comment]
out

**Comment by MasseGuillaume** [comment]
Well done! I'm rebasing and redeploying now.

**Comment by heathermiller** [comment]
AAAIDGIHDGALKDGH2893IUSHEFUAQHGSG!!~! EY YEAAAYYYY!

**Comment by MasseGuillaume** [comment]
@dominv when rebasing I see sass files. Did you decided to go with pure css or it's a merge mistake?

**Comment by MasseGuillaume** [comment]
rebased and merged to master: https://github.com/scalacenter/scastie/commit/0bd5e933e68f9c5548eb436b08bd0150290c5254

Thanks!

**Comment by MasseGuillaume** [comment]
Now live: https://scastie.scala-lang.org/

**Comment by heathermiller** [comment]
SSTRHARHARTIYDYOFODIYETIQYTKKI!!!! Yeeeeaaaaay!

**Comment by heathermiller** [comment]
First observation... There seem to be some issues with the responsive layout. On an iPhone with chrome: 
img_4187
img_4188

If you expand the menu it gets stuck on the out position. 

The layout also seems broken (wide vertical white space bar on mobile phone in chrome, scrolling a bit odd, can't see console + console styling gets weird (changes from dark blue to white)

Overhaul just needs some testing on moniker phones, I think (haven't tried it on a tablet)

**Comment by dominv** [comment]
@MasseGuillaume About the sass' sources, I didn't include them in this initial PR because it was getting to big. But I planned to make a new one including only this sources as well as the needed instructions to compile and use them.

**Comment by MasseGuillaume** [comment]
Can you make a PR that only add the sass files? I will help you with setting up the sbt part.

**Comment by dominv** [comment]
Of course, I'll make it.

**Pull request closed without merging**
