### PR TITLE
Use mongodb to store snippets

### LINKED ISSUE #406: Can't run scala code
Server 128.178.154.84 (scalagesrv1.epfl.ch) has invalid certificate (it has shared certificate from *.scala-lang.org) and because of that I got 503 Service Unavailable response when I wanted to compile & run scala source code on scastie web site. I think that could be a cause of the problem.

### PR DESCRIPTION
**Pull request by MasseGuillaume**
This is a critical fix. Users cannot retrieve their snippets that are older than 2 weeks old, since the network disk we are storing the snippets on is failing.

* ReactiveMongo pull a more recent version of Akka, I had to do modifications to the classpath.
* I wrote a script to scan the old snippet containers
* I implemented an in-memory container to avoid having MongoDB to develop.

fix #406 #391 #378

### CODE REVIEW

**Comment by OlegYch** [comment]
i still think we need a file based container as a backup

**Comment by MasseGuillaume** [comment]
@OlegYch done, added FilesSnippetsContainer

We can swap the container implementation with the configuration key: 

`com.olegych.scastie.balancer.snippets-container = tpe` where `tpe` is one of the following: `mongo`, `memory`, `file`.

**Comment by MasseGuillaume** [comment]
I started the migration script on the server, it's slowly loading data into mongodb.

**Comment by OlegYch** [comment]
@MasseGuillaume great, thank you
any idea about CI failure?

**Pull request merged**
