### PR TITLE
add Scala 2.12.18 and 2.13.11

### PR DESCRIPTION
**Pull request by SethTisue**
not for merge til we actually announce the releases

### CODE REVIEW

**Comment by SethTisue** [comment]
(CI failing til Seb publishes Scala.js)

**Comment by rochala** [comment]
I rerun the tests as the tests are sometimes flaky.

**Comment by SethTisue** [comment]
```
Failed tests:
[error] 	com.olegych.scastie.sbt.SbtActorTest
```

**Comment by rochala** [comment]
One problem is that there are no mtags released yet (thus metals tests are failing), another problem is that SBT can't reload the build according to the tests. I'll have a look at it tomorrow as I need to deploy 3.3.1-RC2 anyway.

**Pull request merged**
