### PR TITLE
Run on Java 17

### PR DESCRIPTION
**Pull request by liff**
Things done:

 - Update JDK packages in `CONTRIBUTING.md` installation instructions,
 - use a recent snapshot of `nixos-unstable`,
 - simplify `default.nix`,
 - update runner base image and
 - replace no longer supported use process PID via reflection with
   the `.pid()` getter.

I tested this locally with `startAll` and by using the runner in the Docker container and it seems to work but I may well have missed something.

### CODE REVIEW

**Comment by OlegYch** [comment]
@liff i had to revert nix env because i get random 'Failed to exec spawn helper' errors when trying to deploy (during calls to docker or ssh)
snippets should still run on java 17, fingers crossed

**Comment by OlegYch** [comment]
@liff doh had to revert running snippets on java 17 because the new module system does not permit to reflectively get pid

**Comment by liff** [comment]
Bummer. I’ll see if I can reproduce the errors at deployment.

**Comment by liff** [comment]
Can you get more details (error code, stack trace) from the “Failed to exec spawn helper” error? There’s a [question](https://stackoverflow.com/questions/61301818/java-failed-to-exec-spawn-helper-error-since-moving-to-java-14-on-linux) about the error on SO that points to the issue possibly having something to with `jspawnhelper`.

So I wonder if the error is from the runners or from sbt in some phase of the deployment?

It looks like adding `-Djdk.lang.Process.launchMechanism=vfork` to somewhere appropriate might do as a workaround but it’d be preferable to have a proper fix.

**Comment by OlegYch** [comment]
it looks like `java.io.IOException: Cannot run program "ssh": error=0, Failed to exec spawn helper: pid: 31668, signal: 11` thrown from `Deployment.scala`, ie during `sbt deploy`
i don't think it could be something with jspawnhelper because sometimes it fails while calling docker and sometimes while calling ssh
i'll try vfork

**Comment by OlegYch** [comment]
@liff looks like vfork worked, java17 is live

**Pull request merged**
