### PR TITLE
Scala 3.1.1 is announced, add suppport for it

### PR DESCRIPTION
**Pull request by vincenzobaz**

### CODE REVIEW

**Comment by OlegYch** [comment]
do we no longer need to publish against 3.0 ?

**Comment by vincenzobaz** [comment]
Scala 3.0.x artifacts can depend on Scala 3.1.y artifacts.

I think we can safely upgrade

**Comment by vincenzobaz** [comment]
If we compile to 3.1.y then snippets in 3.0.x cannot depend on it. Maybe we should wait

**Comment by OlegYch** [comment]
@vincenzobaz please see the build failure

**Pull request merged**
